# Generated by Django 3.2.9 on 2021-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('EmailInfoId', models.AutoField(primary_key=True, serialize=False)),
                ('EmailInfoUserEmail', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
